############################################################################

branches:
    only:
    - master
    - staging
    - trying
    - /^release\/.*$/ # release branches
    - /^v[0-9]+\.[0-9]+\.[0-9]+$/ # version tags

env:
    global:
        - DOCKER_IMAGE_OWNER="dilumaluthge"
        - DOCUMENTER_DEBUG="true"
        - GIT_USER_EMAIL="bcbi-git@brown.edu"
        - GIT_USER_NAME="BCBI Machine Account"
        - JULIA_DEBUG="all"
        - PREDICTMD_OPEN_PLOTS_DURING_TESTS="true"
        - REGISTRY_NAME="BCBIOfflineRegistry"
        - REGISTRY_UUID="226ccab6-caf5-412c-80c4-6c7e3979fa0f"

git:
    depth: 99999999

language: bash

matrix:
    fast_finish: true

notifications:
    email:
        on_failure: always
        on_success: never
os:
    - linux

services:
    - docker

############################################################################

before_install:
    - true
install:
    - true
before_script:
    - true
script:
    - true
after_script:
    - true

############################################################################

stages:
    - "Stage 1 (latex-for-plotting)"
    - "Stage 2 (offlineregistry)"
    - "Stage 3 (predictmd)"

############################################################################

jobs:
    include:
        - stage: "Stage 1 (latex-for-plotting)"
          name: "dilumaluthge/latex-for-plotting"
          env:
              - IMAGE="latex-for-plotting"
          script: ./ci/travis/script.sh
        - stage: "Stage 2 (offlineregistry)"
          name: "dilumaluthge/offlineregistry"
          env:
              - IMAGE="offlineregistry"
          script: ./ci/travis/script.sh
        - stage: "Stage 3 (predictmd)"
          name: "dilumaluthge/predictmd"
          env:
              - IMAGE="predictmd"
          script: ./ci/travis/script.sh

############################################################################
