############################################################################

branches:
    only:
    - master
    - staging
    - trying
    - /^release\/.*$/ # release branches
    - /^v[0-9]+\.[0-9]+\.[0-9]+$/ # version tags

env:
    global:
        - DOCKER_IMAGE_OWNER="dilumaluthge"
        - DOCUMENTER_DEBUG="true"
        - JULIA_DEBUG="all"
        - PREDICTMD_OPEN_PLOTS_DURING_TESTS="true"

git:
    depth: 99999999

language: bash

matrix:
    fast_finish: true

notifications:
    email:
        on_failure: always
        on_success: never
os:
    - linux

services:
    - docker

############################################################################

before_install:
    - true
install:
    - true
before_script:
    - true
script:
    - true
after_script:
    - true

############################################################################

stages:
    - "Stage 1 (latex-for-plotting build-and-test)"
    - "Stage 2 (offlineregistry build-and-test)"
    - "Stage 3 (predictmd build-and-test)"

############################################################################

jobs:
    include:
        - stage: "Stage 1 (latex-for-plotting build-and-test)"
          name: "dilumaluthge/latex-for-plotting"
          env:
              - IMAGE="latex-for-plotting"
          script: ./ci/travis/build-and-test.sh
        - stage: "Stage 2 (offlineregistry build-and-test)"
          name: "dilumaluthge/offlineregistry"
          env:
              - IMAGE="offlineregistry"
          script: ./ci/travis/build-and-test.sh
        - stage: "Stage 3 (predictmd build-and-test)"
          name: "dilumaluthge/predictmd"
          env:
              - IMAGE="predictmd"
              - PREDICTMD_TEST_GROUP="all"
          script: ./ci/travis/build-and-test.sh

############################################################################
